apiVersion: v1
kind: Service

metadata:
  name: "{{ service_name }}"
  labels:
    jobid: "{{ jobid }}"

spec:
  selector:
    jobid: "{{ jobid }}"

  ports:
    - protocol: TCP
      port: 6080
      name: vnc-port

    - protocol: TCP
      port: 6082
      name: cmd-port

    - protocol: TCP
      port: 9222
      name: cdp-browser-port

    - protocol: TCP
      port: 9229
      name: cdp-node-port

